-- Daily Closing Console — initial schema
-- All money is INTEGER halalas (SAR × 100).
-- IDs are TEXT (nanoid-style 16 chars) generated by server/ids.js.
-- Timestamps are INTEGER ms since epoch (Date.now()).

PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;

CREATE TABLE accountants (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  created_at    INTEGER NOT NULL
);

CREATE TABLE brands (
  id            TEXT PRIMARY KEY,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  type          TEXT NOT NULL,
  created_at    INTEGER NOT NULL
);
CREATE INDEX idx_brands_accountant ON brands(accountant_id);

CREATE TABLE branches (
  id            TEXT PRIMARY KEY,
  brand_id      TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  created_at    INTEGER NOT NULL
);
CREATE INDEX idx_branches_brand ON branches(brand_id);
CREATE INDEX idx_branches_accountant ON branches(accountant_id);

CREATE TABLE branch_settings (
  branch_id                    TEXT PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,
  require_network_img          INTEGER NOT NULL DEFAULT 1,
  require_apps_img             INTEGER NOT NULL DEFAULT 1,
  require_cash_img             INTEGER NOT NULL DEFAULT 1,
  require_custody_receipt_img  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE safes (
  id                       TEXT PRIMARY KEY,
  branch_id                TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  accountant_id            TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name                     TEXT NOT NULL,
  opening_balance_halalas  INTEGER NOT NULL DEFAULT 0,
  created_at               INTEGER NOT NULL
);
CREATE INDEX idx_safes_branch ON safes(branch_id);
CREATE INDEX idx_safes_accountant ON safes(accountant_id);

CREATE TABLE employees (
  id                        TEXT PRIMARY KEY,
  branch_id                 TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  accountant_id             TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name                      TEXT NOT NULL,
  custody_balance_halalas   INTEGER NOT NULL DEFAULT 0,
  created_at                INTEGER NOT NULL
);
CREATE INDEX idx_employees_branch ON employees(branch_id);
CREATE INDEX idx_employees_accountant ON employees(accountant_id);

CREATE TABLE cashier_links (
  id            TEXT PRIMARY KEY,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  branch_id     TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  safe_id       TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  employee_id   TEXT REFERENCES employees(id) ON DELETE SET NULL,
  token         TEXT NOT NULL UNIQUE,
  pin_hash      TEXT NOT NULL,
  pin_salt      TEXT NOT NULL,
  pin_version   INTEGER NOT NULL DEFAULT 1,
  status        TEXT NOT NULL DEFAULT 'active', -- active | disabled
  created_at    INTEGER NOT NULL
);
CREATE INDEX idx_links_accountant ON cashier_links(accountant_id);
CREATE INDEX idx_links_branch ON cashier_links(branch_id);
CREATE INDEX idx_links_safe ON cashier_links(safe_id);

CREATE TABLE closings (
  id                        TEXT PRIMARY KEY,
  link_id                   TEXT NOT NULL REFERENCES cashier_links(id) ON DELETE CASCADE,
  accountant_id             TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  branch_id                 TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  safe_id                   TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  employee_id               TEXT REFERENCES employees(id) ON DELETE SET NULL,

  total_sales_halalas       INTEGER NOT NULL,
  network_sales_halalas     INTEGER NOT NULL,
  apps_sales_halalas        INTEGER NOT NULL,
  apps_invoice_count        INTEGER NOT NULL DEFAULT 0,
  cash_sales_halalas        INTEGER NOT NULL, -- computed = total - network - apps
  cash_in_safe_halalas      INTEGER NOT NULL,
  custody_in_hand_halalas   INTEGER NOT NULL DEFAULT 0,
  custody_expense_halalas   INTEGER NOT NULL DEFAULT 0,
  custody_expense_note      TEXT,

  opening_balance_halalas   INTEGER NOT NULL,
  expected_cash_halalas     INTEGER NOT NULL, -- opening + cash_sales
  variance_halalas          INTEGER NOT NULL, -- cash_in_safe - expected

  notes                     TEXT,
  status                    TEXT NOT NULL DEFAULT 'pending', -- pending | confirmed | rejected
  reject_reason             TEXT,
  submitted_at              INTEGER NOT NULL,
  reviewed_at               INTEGER
);
CREATE INDEX idx_closings_accountant_status ON closings(accountant_id, status, submitted_at DESC);
CREATE INDEX idx_closings_safe ON closings(safe_id, submitted_at DESC);
CREATE INDEX idx_closings_branch ON closings(branch_id, submitted_at DESC);

CREATE TABLE attachments (
  id          TEXT PRIMARY KEY,
  closing_id  TEXT NOT NULL REFERENCES closings(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL, -- network | apps | cash | custody_receipt | other
  storage_key TEXT NOT NULL,
  mime        TEXT NOT NULL,
  size        INTEGER NOT NULL,
  created_at  INTEGER NOT NULL
);
CREATE INDEX idx_attachments_closing ON attachments(closing_id);

CREATE TABLE bank_deposits (
  id                  TEXT PRIMARY KEY,
  accountant_id       TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  safe_id             TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  amount_halalas      INTEGER NOT NULL,
  deposit_date        INTEGER NOT NULL,
  receipt_storage_key TEXT,
  note                TEXT,
  created_at          INTEGER NOT NULL
);
CREATE INDEX idx_deposits_safe ON bank_deposits(safe_id, deposit_date DESC);
CREATE INDEX idx_deposits_accountant ON bank_deposits(accountant_id);

-- Ledger for safe balance.
-- type: 'closing_confirm' | 'deposit' | 'opening' | 'adjustment'
-- ref_id: closing_id, deposit_id, etc.
CREATE TABLE cash_movements (
  id                       TEXT PRIMARY KEY,
  safe_id                  TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  type                     TEXT NOT NULL,
  ref_id                   TEXT,
  amount_halalas           INTEGER NOT NULL, -- positive = in, negative = out
  balance_after_halalas    INTEGER NOT NULL,
  created_at               INTEGER NOT NULL
);
CREATE INDEX idx_cash_movements_safe ON cash_movements(safe_id, created_at DESC);

-- Ledger for employee custody.
-- type: 'expense' | 'topup' | 'opening' | 'adjustment'
CREATE TABLE custody_movements (
  id                       TEXT PRIMARY KEY,
  employee_id              TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type                     TEXT NOT NULL,
  ref_id                   TEXT,
  amount_halalas           INTEGER NOT NULL,
  balance_after_halalas    INTEGER NOT NULL,
  created_at               INTEGER NOT NULL
);
CREATE INDEX idx_custody_movements_employee ON custody_movements(employee_id, created_at DESC);

CREATE TABLE pin_attempts (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  link_id     TEXT NOT NULL REFERENCES cashier_links(id) ON DELETE CASCADE,
  ip          TEXT NOT NULL,
  success     INTEGER NOT NULL,
  created_at  INTEGER NOT NULL
);
CREATE INDEX idx_pin_attempts_link_time ON pin_attempts(link_id, created_at);
CREATE INDEX idx_pin_attempts_ip_time ON pin_attempts(ip, created_at);

CREATE TABLE signup_attempts (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ip          TEXT NOT NULL,
  created_at  INTEGER NOT NULL
);
CREATE INDEX idx_signup_attempts_ip_time ON signup_attempts(ip, created_at);

CREATE TABLE audit_log (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  accountant_id TEXT NOT NULL,
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,
  before_json   TEXT,
  after_json    TEXT,
  created_at    INTEGER NOT NULL
);
CREATE INDEX idx_audit_accountant_time ON audit_log(accountant_id, created_at DESC);
