-- Daily Closing Console — Postgres schema for Neon
-- All money is BIGINT halalas (SAR × 100).
-- IDs are TEXT (16-char nanoid-style) generated by api/_lib/ids.js.
-- Timestamps are BIGINT ms since epoch (Date.now()).

CREATE TABLE IF NOT EXISTS accountants (
  id            TEXT PRIMARY KEY,
  email         TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  created_at    BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS brands (
  id            TEXT PRIMARY KEY,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  type          TEXT NOT NULL,
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_brands_accountant ON brands(accountant_id);

CREATE TABLE IF NOT EXISTS branches (
  id            TEXT PRIMARY KEY,
  brand_id      TEXT NOT NULL REFERENCES brands(id) ON DELETE CASCADE,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_branches_brand ON branches(brand_id);
CREATE INDEX IF NOT EXISTS idx_branches_accountant ON branches(accountant_id);

CREATE TABLE IF NOT EXISTS branch_settings (
  branch_id                    TEXT PRIMARY KEY REFERENCES branches(id) ON DELETE CASCADE,
  enable_apps_sales            INTEGER NOT NULL DEFAULT 1,
  require_foodics_img          INTEGER NOT NULL DEFAULT 1,
  require_network_img          INTEGER NOT NULL DEFAULT 1,
  require_apps_img             INTEGER NOT NULL DEFAULT 1,
  require_cash_img             INTEGER NOT NULL DEFAULT 1,
  require_custody_receipt_img  INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS safes (
  id                       TEXT PRIMARY KEY,
  branch_id                TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  accountant_id            TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name                     TEXT NOT NULL,
  opening_balance_halalas  BIGINT NOT NULL DEFAULT 0,
  created_at               BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_safes_branch ON safes(branch_id);
CREATE INDEX IF NOT EXISTS idx_safes_accountant ON safes(accountant_id);

CREATE TABLE IF NOT EXISTS employees (
  id                        TEXT PRIMARY KEY,
  branch_id                 TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  accountant_id             TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  name                      TEXT NOT NULL,
  custody_balance_halalas   BIGINT NOT NULL DEFAULT 0,
  created_at                BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_employees_branch ON employees(branch_id);
CREATE INDEX IF NOT EXISTS idx_employees_accountant ON employees(accountant_id);

CREATE TABLE IF NOT EXISTS cashier_links (
  id            TEXT PRIMARY KEY,
  accountant_id TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  branch_id     TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  safe_id       TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  employee_id   TEXT REFERENCES employees(id) ON DELETE SET NULL,
  token         TEXT NOT NULL UNIQUE,
  pin_hash      TEXT NOT NULL,
  pin_salt      TEXT NOT NULL,
  pin_version   INTEGER NOT NULL DEFAULT 1,
  status        TEXT NOT NULL DEFAULT 'active',
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_links_accountant ON cashier_links(accountant_id);
CREATE INDEX IF NOT EXISTS idx_links_branch ON cashier_links(branch_id);
CREATE INDEX IF NOT EXISTS idx_links_safe ON cashier_links(safe_id);

CREATE TABLE IF NOT EXISTS closings (
  id                        TEXT PRIMARY KEY,
  link_id                   TEXT NOT NULL REFERENCES cashier_links(id) ON DELETE CASCADE,
  accountant_id             TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  branch_id                 TEXT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  safe_id                   TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  employee_id               TEXT REFERENCES employees(id) ON DELETE SET NULL,

  total_sales_halalas       BIGINT NOT NULL,
  network_sales_halalas     BIGINT NOT NULL,
  apps_sales_halalas        BIGINT NOT NULL,
  apps_invoice_count        INTEGER NOT NULL DEFAULT 0,
  cash_sales_halalas        BIGINT NOT NULL,
  cash_in_safe_halalas      BIGINT NOT NULL,
  custody_in_hand_halalas   BIGINT NOT NULL DEFAULT 0,
  custody_expense_halalas   BIGINT NOT NULL DEFAULT 0,
  custody_expense_note      TEXT,

  keeta_halalas             BIGINT NOT NULL DEFAULT 0,
  hungerstation_halalas     BIGINT NOT NULL DEFAULT 0,
  jahez_halalas             BIGINT NOT NULL DEFAULT 0,
  ninja_halalas             BIGINT NOT NULL DEFAULT 0,

  opening_balance_halalas   BIGINT NOT NULL,
  expected_cash_halalas     BIGINT NOT NULL,
  variance_halalas          BIGINT NOT NULL,

  notes                     TEXT,
  status                    TEXT NOT NULL DEFAULT 'pending',
  reject_reason             TEXT,
  submitted_at              BIGINT NOT NULL,
  reviewed_at               BIGINT
);
CREATE INDEX IF NOT EXISTS idx_closings_accountant_status ON closings(accountant_id, status, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_closings_safe ON closings(safe_id, submitted_at DESC);
CREATE INDEX IF NOT EXISTS idx_closings_branch ON closings(branch_id, submitted_at DESC);

CREATE TABLE IF NOT EXISTS attachments (
  id          TEXT PRIMARY KEY,
  closing_id  TEXT NOT NULL REFERENCES closings(id) ON DELETE CASCADE,
  kind        TEXT NOT NULL,
  storage_key TEXT NOT NULL,
  mime        TEXT NOT NULL,
  size        BIGINT NOT NULL,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_attachments_closing ON attachments(closing_id);

CREATE TABLE IF NOT EXISTS bank_deposits (
  id                  TEXT PRIMARY KEY,
  accountant_id       TEXT NOT NULL REFERENCES accountants(id) ON DELETE CASCADE,
  safe_id             TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  amount_halalas      BIGINT NOT NULL,
  deposit_date        BIGINT NOT NULL,
  receipt_storage_key TEXT,
  note                TEXT,
  created_at          BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_deposits_safe ON bank_deposits(safe_id, deposit_date DESC);
CREATE INDEX IF NOT EXISTS idx_deposits_accountant ON bank_deposits(accountant_id);

CREATE TABLE IF NOT EXISTS cash_movements (
  id                       TEXT PRIMARY KEY,
  safe_id                  TEXT NOT NULL REFERENCES safes(id) ON DELETE CASCADE,
  type                     TEXT NOT NULL,
  ref_id                   TEXT,
  amount_halalas           BIGINT NOT NULL,
  balance_after_halalas    BIGINT NOT NULL,
  created_at               BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_cash_movements_safe ON cash_movements(safe_id, created_at DESC);

CREATE TABLE IF NOT EXISTS custody_movements (
  id                       TEXT PRIMARY KEY,
  employee_id              TEXT NOT NULL REFERENCES employees(id) ON DELETE CASCADE,
  type                     TEXT NOT NULL,
  ref_id                   TEXT,
  amount_halalas           BIGINT NOT NULL,
  balance_after_halalas    BIGINT NOT NULL,
  created_at               BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_custody_movements_employee ON custody_movements(employee_id, created_at DESC);

CREATE TABLE IF NOT EXISTS pin_attempts (
  id          BIGSERIAL PRIMARY KEY,
  link_id     TEXT NOT NULL REFERENCES cashier_links(id) ON DELETE CASCADE,
  ip          TEXT NOT NULL,
  success     INTEGER NOT NULL,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_pin_attempts_link_time ON pin_attempts(link_id, created_at);
CREATE INDEX IF NOT EXISTS idx_pin_attempts_ip_time ON pin_attempts(ip, created_at);

CREATE TABLE IF NOT EXISTS signup_attempts (
  id          BIGSERIAL PRIMARY KEY,
  ip          TEXT NOT NULL,
  created_at  BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_signup_attempts_ip_time ON signup_attempts(ip, created_at);

CREATE TABLE IF NOT EXISTS audit_log (
  id            BIGSERIAL PRIMARY KEY,
  accountant_id TEXT NOT NULL,
  action        TEXT NOT NULL,
  entity_type   TEXT NOT NULL,
  entity_id     TEXT NOT NULL,
  before_json   TEXT,
  after_json    TEXT,
  created_at    BIGINT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_accountant_time ON audit_log(accountant_id, created_at DESC);
